version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  redis:
    driver: local
